# Configuration d'analyse optimisée pour CI/CD
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    # Transformer les erreurs en warnings
    deprecated_member_use: warning
    deprecated_member_use_from_same_package: warning
    use_build_context_synchronously: warning
    invalid_annotation_target: ignore
    todo: ignore

linter:
  rules:
    # Désactiver les règles problématiques
    avoid_print: false
    prefer_single_quotes: false
