name: vraiauth
description: "A new Flutter project."

publish_to: 'none' # Retirer si publication sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.1.0

  # MVVM + API
  provider: ^6.1.2
  http: ^1.2.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  flutter_stripe: ^12.0.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/products.json
