// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDL80ooEJpw9G4yF9BYibhbRoqjz8AKkk',
    appId: '1:100846685226:web:f48baa51884b7f4f0cc753',
    messagingSenderId: '100846685226',
    projectId: 'commerce-c602b',
    authDomain: 'commerce-c602b.firebaseapp.com',
    storageBucket: 'commerce-c602b.firebasestorage.app',
    measurementId: 'G-XZ7NMCE6BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPba4bhlsk1TdoN79tRjUqvRfKizE4YFQ',
    appId: '1:100846685226:android:49d193b5980352410cc753',
    messagingSenderId: '100846685226',
    projectId: 'commerce-c602b',
    storageBucket: 'commerce-c602b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHghNUnZjSZfXg9uifkanRz7WH8PERNLE',
    appId: '1:100846685226:ios:5ff945d7cfdcf1fe0cc753',
    messagingSenderId: '100846685226',
    projectId: 'commerce-c602b',
    storageBucket: 'commerce-c602b.firebasestorage.app',
    iosClientId:
        '100846685226-mos0uivbvu41n9bfvgpar17474sq8m9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.vraiauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHghNUnZjSZfXg9uifkanRz7WH8PERNLE',
    appId: '1:100846685226:ios:5ff945d7cfdcf1fe0cc753',
    messagingSenderId: '100846685226',
    projectId: 'commerce-c602b',
    storageBucket: 'commerce-c602b.firebasestorage.app',
    iosClientId:
        '100846685226-mos0uivbvu41n9bfvgpar17474sq8m9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.vraiauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDL80ooEJpw9G4yF9BYibhbRoqjz8AKkk',
    appId: '1:100846685226:web:610b5aa7c7ec49860cc753',
    messagingSenderId: '100846685226',
    projectId: 'commerce-c602b',
    authDomain: 'commerce-c602b.firebaseapp.com',
    storageBucket: 'commerce-c602b.firebasestorage.app',
    measurementId: 'G-BGK5J2NB1R',
  );
}
